<?php

/**
 * @file
 * Module file for ycloud_vy_updates.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for \Drupal\system\Form\SiteInformationForm.
 */
function ycloud_vy_updates_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {

  $current_user = \Drupal::currentUser()->getRoles();

  // Disable timezones for users other than admin.
  if (!in_array('administrator', $current_user)) {
    $form['site_information']['site_mail']['#attributes']['disabled'] = 'disabled';
  }
}
